# Netlify configuration for Dialettami
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# (Opzionale) Redirect per SPA o percorsi puliti
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
